language: elixir
matrix:
  include:
    - otp_release: 20.2
      elixir: 1.6.0
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
  - mix format --check-formatted
  - mix credo
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix coveralls.travis
  - MIX_ENV=docs mix inch.report