language: elixir
elixir: 1.1.1
otp_release:
  - 18.0
sudo: false # to use faster container based build environment
after_script:
  - MIX_ENV=docs mix coveralls.travis
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report