language: elixir
matrix:
  include:
    - otp_release: 19.2
      elixir: 1.3.4
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix coveralls.travis
  - MIX_ENV=docs mix inch.report